---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-app
  namespace: default
  labels:
    app: cors-app
    version: v1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: cors-app
  template:
    metadata:
      labels:
        app: cors-app
        version: v1
    spec:
      containers:
      - name: cors-app
        image: quay.io/kutsav/cors-app:1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 2

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: cors-app
  namespace: default
  labels:
    app: cors-app
spec:
  selector:
   app: cors-app
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP
